### ISSUE TITLE
Tiny Tiny RSS API not working with Yunohost

### ISSUE THREAD

**Issue by lapineige** [plopoyop/freshrss_ynh#11]
Hello,

I'm trying to use a tiny tiny rss client with freshrss on yunohost. I installed this extension: https://github.com/FreshRSS/Extensions/tree/master/xExtension-TTRSS_API
But with the default configuration, every client don't work - they can't connect. I tried to skip the sso login stage, with sudo yunohost app setting freshrss skipped_uris -v "/". If I do that, the answer is 405 not allowed.
Do you know if I have any thing to change is the configuration files ?

It could also be an issue with the extension, should I try to report it on the extension's github repository ?

Thanks.

**Comment by plopoyop** [comment]
Hello,
I just read quickly how to access to the extention.

You should try : 
skipped_uris: /api/ttrss.php

Before trying to use the client, try to access to the API using your web browser (that's how I debugged the access to the official API). If you see SSOWAT portal, it's still not good. It's easier that way than using the client without any debug information.

good luck.

**Comment by lapineige** [comment]
Thx for the quick answer.

I forgot a lot of details, sorry.
The skipped_uris are:
mydomain/fressh
mydomain/fressh/api/ttrss.php
mydomain/fressh/i/api/ttrss.php # because when I try it with the browser, it redirect to this one.

When I connect from my browser, I have this error: {"seq":0,"status":1,"content":{"error":"NOT_LOGGED_IN"}}
Some client just say hat there is an error while authenticating, others just wait forever (same before adding skipped_uris).
If I use mydomain/fressh/api/ttrss.php instead of mydomain/fressh/, I have this kind of message: "Login error, it seems you provided a wrong username or password" (but they are correct).

**Comment by lapineige** [comment]
Strange... after a server reboot, even if I did "yunohost app ssowatconf" before, it's working with this adress: mydomain/fressh/api/ttrss.php

Issue solved, thanks for your time. I'll post it on yunohost forum.

**Comment by plopoyop** [comment]
Ok,
great :+1:
